src/Copy/Text.elm, src/Page/Events.elm, src/Theme/PageHeader.elm, tests/Page/EventsTests.elm
Fixes #215 
- Still working on, but putting up for review so @katjam can keep an eye / make suggestions if you want
So far:
- Made buttons larger
- Removed 'all events' from main list and stuck it underneath
- Hid left/right arrows on desktop view, since theyre not needed now all events isn't stretching the container
=> WIP: Pagination control improvements

src/Data/PlaceCal/Events.elm, src/Data/TestFixtures.elm, src/Messages.elm, src/Page/Events.elm, src/Page/Index.elm, src/Shared.elm, tests/Page/AboutTests.elm, tests/Page/EventTests.elm, tests/Page/EventsTests.elm, tests/Page/IndexTests.elm, tests/Page/JoinUsTests.elm, tests/Page/NewsItemTests.elm, tests/Page/NewsTests.elm, tests/Page/PartnerTests.elm, tests/Page/PartnersTests.elm, tests/Page/PrivacyTests.elm
Fixes #259
- Only feature future events on homepage
=> fix: Only feature future events on home

content/about/accessibility.md, src/Copy/Text.elm
Fixes #263 
- State WCAG 2.1 AA aim
- Featured --> Upcoming Events
- Remove "near you" from link to all events
=> Minor copy changes in response to partner testing

src/Copy/Keys.elm, src/Copy/Text.elm, src/Page/JoinUs.elm, src/Theme/PageFooter.elm, src/Theme/PageHeader.elm
Fixes #275 
- White placeholder text
- Dark blue main navigation
=> Make placeholder text white & navigation dark blue

README.md, src/Copy/Text.elm, src/Page/Events/Event_.elm, src/Page/Partners/Partner_.elm, tests/Page/PartnerTests.elm
Fixes #279
Algorithm for sanitizing URLs on Partner page
=> URL protocol stripping

src/Theme/PageFooter.elm
Fixes #277
In the footer
- more L/R padding on signup button
- signup button jumps to full width on mobile
- GI logo is centered on mobile
=> Footer styling tweaks

src/Helpers/TransRoutes.elm, src/Theme/PageHeader.elm
Is now part of the menu options
Fixes #276
=> Donate button on mobile burger menu

.github/workflows/build.yml
Fixes #287
Untested, but the worst that happens is that it does nothing.
=> Run the Netlify build every 12 hours

public/index.js
=> Chore: removed hotjar tracking code

src/Shared.elm, src/View.elm
Fixes #272 
Plausible tracking script
=> Chore: add tracking script to page

src/Copy/Keys.elm, src/Copy/Text.elm, src/Data/PlaceCal/Events.elm, src/Data/TestFixtures.elm, src/Page/Events/Event_.elm, tests/Page/EventTests.elm, tests/Page/PartnerTests.elm
Closes #223 
When showing an event page, display a link to the user supplied 'publisherUrl' if present.
(Expecting feedback on the layout)
=> Feature: show event publisher url if present

src/View.elm
Fixes #183 
- swapped out typeKit url
- checked events list and single pages with visual diffing tool
=> update external css to resource managed by Gendered Intelligence

.env.example, .gitignore, README.md, elm-constants.json, package-lock.json, package.json, src/Api.elm, src/Constants.elm, src/Page/JoinUs.elm, src/Site.elm
Fixes #299 
Use of environment variables. A sample environment file is provided.
=> Use environment variables for critical values

src/Theme/PageHeader.elm
This is faster than the standard transitions, but matches the footer.
=> Transition header link colour and border at same rate

src/Page/Partners.elm
=> Show area tags as a row

src/Data/PlaceCal/Events.elm
Temp Solution for #348 
- Reduce date range of loaded events temporarily to make build faster
=> fix: reduce range of loaded event dates temporarily.

src/Theme/Global.elm
=> Tabbable input fields on JoinUs checkboxes

src/Data/PlaceCal/Events.elm
Fixes #389
Window extended to 1st of January, 2030. Should be enough?
=> Extend API event import window

src/Data/PlaceCal/Events.elm
Fixes #
- 6 months in the past
- 6 months in the future
We should really figure out how to pass this in as a flag but lets show people future events while we figure it out..
=> manually update events query

elm.json
Fixes #397 
- Rename `date-format` package
=> fix: Update package name

app/Route/Privacy.elm, src/Theme/TextHeavyPage.elm, src/Theme/TransMarkdown.elm
Partial #412 
- Adds privacy page
- Start to store markdown blocks as data rather than html
=> WIP add Privacy page and store markdown blocks

src/Theme/AboutPage.elm, src/Theme/PageTemplate.elm
Partial #412 
- clears out some unused imports
=> style: Remove unused imports

app/Route/News.elm, elm.json, src/Data/PlaceCal/Articles.elm, src/Data/PlaceCal/Events.elm, src/Data/PlaceCal/Partners.elm, src/Helpers/TransDate.elm, src/Theme/AboutPage.elm, src/Theme/NewsPage.elm
Partial #412
- Adds News index
=> feat: Add News decoders and News index page

app/Route/News/NewsItem_.elm, src/Theme/NewsItemPage.elm, src/Theme/NewsPage.elm
Partial #412 
- Add route and render function for individual News items
Implement paginator on single news item pages
=> feat: Add News item page routes

app/Route/About.elm, app/Route/Partners.elm, app/Route/Privacy.elm, src/Theme/PartnersPage.elm
Partial #412 
- Add partners index
=> Add partners index and remove unused map to Msg

app/Route/Partners/Partner_.elm, src/Theme/PartnerPage.elm
Partial #412 
- Add single Partner page (without event listing)
=> Add Partner single page without events

src/Copy/Text.elm
Fixes #407
- Change registered office address to '200a Pentonville Road'
=> Update Trans Dimension registered office

src/Theme/Global.elm
Fixes #416
- Update hex value for dark purple colour to that suggested in #416
=> Update hex value to suggested value

src/Copy/Text.elm
Fixes #417
- Update URL for Studio Squid
=> Update Squid URL

app/Shared.elm, src/Copy/Keys.elm, src/Copy/Text.elm, src/Helpers/TransDate.elm, src/Theme/PageFooter.elm
Fixes #410
- Adds helper function to get human-readable year from POSIX time
- Inserts current year into copyright text
=> Update copyright year

src/Data/PlaceCal/Articles.elm, src/Theme/AboutPage.elm, src/Theme/PageTemplate.elm
Partial #412 
About page header & tighten imports
=> Add in About heading & tidy some styles

app/Route/Events.elm, app/Route/Events/Event_.elm, app/Route/Index.elm, src/Data/PlaceCal/Events.elm, src/Data/PlaceCal/Partners.elm, src/Theme/EventPage.elm, src/Theme/EventsPage.elm, src/Theme/IndexPage.elm
Fixes #412
- Populates index page in v3 style
- Some tidy of events
=> Re-jig events data views and add content to index

app/Route/News/NewsItem_.elm, src/Data/PlaceCal/Articles.elm, src/Theme/NewsItemPage.elm, src/Theme/NewsPage.elm
Partial #412
- Adds stock image to news on data import if article doesn't have one.
=> Add image to news

app/Route/JoinUs.elm, src/Theme/JoinUsPage.elm
Fixes #442 
- Add join us form to v3
=> Join form page

src/Copy/Text.elm
Closes #411
Before merging need to:
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNkZmU4YWU3Y2M1YTc4NTQyZTVjYzEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.NecKAGQfQFUrpNftblM-Qa_o-92dbqC_dZyVX_VWSuM">Huly&reg;: <b>TD-457</b></a></sub>
=> Update donation link

app/Route/Events.elm, app/Route/Index.elm, app/Route/Partners.elm, app/Shared.elm, src/Data/PlaceCal/Partners.elm
Partial #466
- Add filter param
- Persist filter between pages
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzUzM2MyYmQyZWY0Y2JjYzQ2ZjY5MmEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.1kW_9W6IaaHUHKsJuT2AMDWchkZpXq4XfG-9Gx_BSHc">Huly&reg;: <b>TD-470</b></a></sub>
=> Enable link with filter preset to Events, Index and Partners

app/Route/Events/Event_.elm, app/Route/News/NewsItem_.elm, src/Copy/Keys.elm, src/Copy/Text.elm, src/Data/PlaceCal/Articles.elm, src/Helpers/TransRoutes.elm, src/Theme/Page/News.elm, src/Theme/PageTemplate.elm
Closes #479.
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdjNWE4N2YxNDRmNTg1YWU1MmViNDYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9._rwgoyh7mXycbCGLNy7qdSmtltRcv-Er8omB1fVbDMU">Huly&reg;: <b>TD-488</b></a></sub>
=> [WIP] Fix: open graph metadata

app/Shared.elm, app/View.elm, elm-pages.config.mjs
=> move font preload into vite config
