geeksforsocialchange/the-trans-dimension

src/Page/News.elm, src/Page/News/NewsItem_.elm
Fixes #202
- List bullet does not appear if there are no partners affiliated with an article
=> fix: Only display partner list in article header if there is one

src/Copy/Keys.elm, src/Copy/Text.elm, src/Page/Partners/Partner_.elm
Fixes #280
On partner show page
- default text when missing partner description
- padding above description
=> Partner page layout tweaks

src/Data/PlaceCal/Articles.elm, src/Data/TestFixtures.elm, src/Page/News.elm, src/Page/News/NewsItem_.elm, tests/Page/NewsItemTests.elm
Fixes #137
News items have images that come from PC API. (or filler image if none present). Work done to news data, index and show code files
=> News item images

src/Copy/Keys.elm, src/Copy/Text.elm, src/Page/Events/Event_.elm
Relates to #240
We now include the partner's name in the button to find all partner events.
If we don't have a partner's name for some reason, we fall back to "this partner" instead.
I'm assuming that "{partner_name}'s" is always the correct grammar. I haven't thought about it very hard, though.
=> Indicate whose events we're linking people to

src/Copy/Text.elm, src/Page/Events/Event_.elm, src/Page/News.elm, src/Page/News/NewsItem_.elm, src/Page/Partners/Partner_.elm
Closes #309 
Only allow URLs with HTTPS schema.
Models:
- Partner (url, logo)
- Event (n/a at the moment)
- NewsItem (image)
Views:
- Partner: index, show
- Event: show (uses parter.url)
- News: index, show
=> Bug: validate URLs coming from API.

src/Copy/Keys.elm, src/Copy/Text.elm, src/Page/Partners/Partner_.elm
Fixes #264
On show partner page, a link is rendered below the address that will take them to a google map page in a new tab
=> Feature: Partner google map link

src/Copy/Text.elm, src/Data/PlaceCal/Events.elm, src/Helpers/TransDate.elm, src/Page/Events.elm
Fixes #282
On Events page, when 'all events' is selected, only show events after the current day.
=> Fix: only show events in the future

src/Copy/Keys.elm, src/Copy/Text.elm, src/Data/PlaceCal/Events.elm, src/Helpers/TransDate.elm, src/Page/Events.elm, src/Page/Index.elm, src/Page/Partners/Partner_.elm, tests/Page/EventsTests.elm
Fixes #282
Builds on #307, review and merge that first.
We add a "Past events" button to the interface.
In order to do this, I also improved the interface for the filters to rely on a custom `Filter` type instead of a `Maybe` for more expressive filtering.
I also wrapped the event list we expose to other parts of the app so it doesn't need to worry about the filtering and just provides the events.
=> Filter events by the past as well as the future

src/Page/News.elm, src/Page/News/NewsItem_.elm
Relates to #137
I chose article length because it looks like the existing articles all have the same publication datetime (probably because they're published at midnight or something). Article length felt random enough to create a decent amount of variation.
=> Select default news image based on article length

src/Page/Events.elm, src/Page/Events/Event_.elm, src/Page/Partners/Partner_.elm, tests/Page/EventTests.elm, tests/Page/PartnerTests.elm
Closes #240
When clicking the "Events by <partner name>" button on an events page, we now navigate to the events section of the partner page instead of the top of the page.
=> Scroll to events

src/Page/Index.elm, src/Page/News.elm, src/Theme/Global.elm
Closes #243
- We give news items a dark blue background for consistency with the expanded news item page and the rest of the site and because we have established styles for links on non-white backgrounds
- We link from the title of the news list item to the news item page
I decided not to hide one of the links from screen readers because there's a bunch of the news article text in the middle, making it valuable to have both links announced. They go to the same place, but have different link text, so we don't have the issue of repetitive links.
=> Link news list item titles to news items

src/Helpers/TransDate.elm
I was confused when reading this code and didn't understand why we were still using UTC everywhere but weren't displaying the wrong times (or were we) and ultimately traced it back to converting ISO timestamps from PlaceCal using `Iso8601.toTime`, which always outputs in UTC.
This change clarifies that that's the assumption being made here.
=> Document why we use UTC

src/Page/Events/Event_.elm
We borrow the styles directly from partners.
=> Parse markdown event descriptions

src/Theme/PageFooter.elm
Fixes #338 
- convert span "heading" to a label
- avoids visual regression
- doesn't *look* like a label so although it is clickable and helpful to screen readers I am not sure if someone looking at the site would attempt to use it in that way.
=> add label to signup form for accessibilty

src/Page/Partners.elm
Fixes #352
On /partners only show pins on the map from partners with no service areas
=> Only show partners without service areas on map

src/Page/Partners/Partner_.elm
Fixes #353 
This data comes from PlaceCal where partner admins can upload any arbitrary image (not just a logo) so sometimes this is a picture of their group or facilities. Furthermore: if this is a logo we don't have any way of making the logo look correct on the TD page which is important if they have a transparent PNG with dark text.
=> Remove partner logo from show partner page

src/Data/PlaceCal/Events.elm, src/Data/PlaceCal/Partners.elm, src/Page/Partners.elm, src/Theme/Global.elm
Fixes #379 
- Temporarily allow address values from PlaceCal to have missing lat and long
- Default to 0, 0 and do not render in maps
=> fix: Allow for geo data to contain null Lat or Long (temporary)

src/Copy/Keys.elm, src/Copy/Text.elm, src/Page/Events.elm, tests/Page/EventsTests.elm
Fixes #361 
- When a partner has > 20 events and `past events` is selected, if none exist then the text shown now is 
> There were no past events.
- A test has been added to catch this edge case
Please let me know what the copy should be here if this is not suitable - I just went with something simple for now!
=> Improve text shown for past events when none exist 

src/Page/Index.elm, src/Theme/PageTemplate.elm
- Use alt text instead of complex hidden images and visibly hidden spans.
- Drop the invisible and confusing link to the home page. We already have a link to take us home in the header, and this one had no indication it was a link and a very wide catchment area for that link.
This change brought to you by me scrolling to the top of the page and clicking somewhere on the background and being navigated somewhere very unexpectedly.
=> Improve logo markup

src/Copy/Keys.elm, src/Copy/Text.elm, src/Data/PlaceCal/Partners.elm, src/Page/Partners/Partner_.elm, tests/Page/PartnerTests.elm, tests/TestFixtures.elm
Fixes #400
- Covert `partner.contactDetails` to a `Maybe`
- Add empty text to Contact details section on Partner view
- Amend tests for new cases
=> fix: Expect contact details to maybe be empty

src/Data/PlaceCal/Events.elm, src/Data/PlaceCal/Partners.elm
Fixes #402 
- Allow partner contact to contain `null` for contact phone or email
- Import events Jan 2024 to June 2025
=> fix: Allow events up to June 2025. Allow null partner telephone or email

.github/workflows/build.yml
- We moved from GI to GFSC cloudflare host
- The cron that runs every 3 hours relies on a deploy hook
=> Update build.yml with new deploy hook following Cloudflare account move

app/Route/Events.elm, app/Route/Index.elm, app/Route/Partners/Partner_.elm, src/Copy/Keys.elm, src/Copy/Text.elm, src/Data/PlaceCal/Events.elm, src/Data/PlaceCal/Partners.elm, src/Theme/Page/Events.elm, src/Theme/Page/Index.elm, src/Theme/Page/Partner.elm, src/Theme/Paginator.elm, src/Theme/RegionSelector.elm
Fixes #408
- Adds regional selector to index page
- Moves event lists out of model & instead calculate from filters
- Correct featured events on index to show draw from all future, not just today
TODO: Would like to add tests for event listings
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJlNTllNGU3Y2M1YTc4NTQyOTk0OWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.6sYBEmyV2h63ye48FPotHgVNikrmCyXvBN_xRYIol54">Huly&reg;: <b>TD-453</b></a></sub>
=> feat: Filter by date and region on index, events and partner pages

app/Route/Partners.elm, src/Copy/Keys.elm, src/Copy/Text.elm, src/Data/PlaceCal/Partners.elm, src/Theme/Page/Partners.elm
Fixes #464
Fixes #408 
- Adds region filter to partners index page
- Alphabetises list of partners everywhere so regional partners are intermingled
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQzNGUzZWQyZWY0Y2JjYzQ2ODZmNjYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.TrWZbA-ilZSbOoCNl02_u2L4J6yXCMQbAbUzRAwGbPo">Huly&reg;: <b>TD-466</b></a></sub>
=> feat: Add filter by region to Partners index

content/about/main.md
Fixes #463
- Link to get in touch has mailto prefix
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1YTUzYTFlMDYzMmRkMDhlMjU3YWUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.Lg6MJsjx6WFXSFgNNsWG2BLOE9nPm2O317GCiw_cmMQ">Huly&reg;: <b>TD-472</b></a></sub>
=> fix mailto link in about

src/Data/PlaceCal/Partners.elm, src/Theme/Page/Partner.elm
Fixes #472
- Added Instagram URL to Partner type, query and decoder
- Added Instagram URL to Partner view
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzVmMTUwZmYxNDRmNTg1YWU0ZDY0NjgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.Dd6LVVUdB_rdufy9enw5TQlEa_k3mTpM-zL_5Kx1w9U">Huly&reg;: <b>TD-478</b></a></sub>
=> fix: Show Instagram URL under Partner contact details

src/Copy/Keys.elm, src/Copy/Text.elm, src/Theme/Page/Partner.elm
Fixes #433
Shows summary and description on show pages.
Note that this bug existing has resulted in people improvising in the backend repeating info - example below. We may need to do some post-fix cleanup.
Screenshot showing change vs original bug ticket:
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNlMGQ2M2U3Y2M1YTc4NTQyZTVlN2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.cnX74TV1oKygD20MDP1CW0K_oxUE0PLOAI1e1uhNxdo">Huly&reg;: <b>TD-458</b></a></sub>
=> fix: add summary to partner show pages

src/Data/PlaceCal/Events.elm, src/Theme/Page/Partner.elm, src/Theme/Paginator.elm
Fixes #478
- Fixes incorrect filter applied to future event listings on Partner page
- Updates misleading function name
GFSC Partner page after fix:
Mxer MCR Partner page after fix:
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzYxOWU5NGYxNDRmNTg1YWU0ZGNhMjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.RLaqiEb8WcqFfJP5SMaQxEOpisH0G8V_fbZbqGIMl34">Huly&reg;: <b>TD-482</b></a></sub>
=> fix: Show future events

src/Theme/PageTemplate.elm
Fixes #476 
- The rendered HTML was missing a `viewport` meta tag, which is required for responsiveness on mobile devices (https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag)
- This tag has been added to `pageMetaTags` to apply to all pages
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY0MDZmZWYxNDRmNTg1YWU0ZTNiNmYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.NGy09T9E1RI49Tho-ly39Flzid17-gdryx-CfXCl8tA">Huly&reg;: <b>TD-485</b></a></sub>
=> fix: Enable responsive UI on mobile devices

app/Route/Events/Event_.elm, src/Copy/Keys.elm, src/Copy/Text.elm
Closes #488.
Add date, time, host and description to event op tags.
Also fix a buggy behavior in the event page where the "All events by" button always display "All events by this partner" instead of "All events by {{ partner-name }}"
<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdlZGI3N2YxNDRmNTg1YWU1MzRlMjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.QqdFuwjCUxGERiv1ywt-vdz62EwKAK3c1vJF0KyAJeg">Huly&reg;: <b>TD-490</b></a></sub>
=> Improve event metadata

src/Theme/Page/Partner.elm
Fixes #358 
Margin on the pages without maps was too small leading to 'cramped look'. Changed layout so more of a gap for cleaner look.
Before:
After:
=> Change margin on the Partner pages without maps.

.github/workflows/build.yml
Builds are now sub 5 minutes thanks to the great work by @mateusfpleite so propose we increase this as currently it can be a very long delay between PlaceCal update and the info going live.
It looks like the previous limit was removed entirely also but might be set to 3,000 minutes in the future.
If this works let's reduce it to every 30 mins.
https://developers.cloudflare.com/workers/ci-cd/builds/limits-and-pricing/
=> Increase cron frequency

.husky/pre-commit, README.md, package-lock.json, package.json
Closes #503.
Uses [husky](https://typicode.github.io/husky/) and [lint-staged](https://github.com/lint-staged/lint-staged) to run elm-format on all staged Elm files whenever a commit is created.
=> Set up pre-commit to run elm-format

src/Theme/Page/Events.elm, src/Theme/Page/Index.elm, src/Theme/Page/Partners.elm, src/Theme/RegionSelector.elm
Fixes #507
- Shows region selector for sites with more than one partnership, hides otherwise
Tested using `PARTNERSHIP_TAG_LIST=3|London`:
=> fix: Only show region selector for sites with more than one partnership
